# Use the official Python 3.8 image as the base image
FROM python:3.8

# Install curl and required dependencies for Yarn
RUN apt-get update && apt-get install -y curl gnupg

# Add Yarn's GPG key and repository
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Install Yarn
RUN apt-get update && apt-get install -y yarn

# Install Node.js v18.x
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

# Set the working directory
WORKDIR /app

COPY ../alto-launcher.sh /app

RUN git clone https://github.com/eth-infinitism/bundler-spec-tests.git

WORKDIR /app/bundler-spec-tests

# Install PDM
RUN pip install pdm

# Install dependencies
RUN pdm install && pdm run update-deps

# Expose bundler and Ethereum node ports
EXPOSE 3000 8545

# Set the environment variables for the test suite
ENV BUNDLER_URL=http://localhost:3000/rpc
ENV ENTRY_POINT=0x5fbdb2315678afecb367f032d93f642f64180aa3
ENV ETHEREUM_NODE=http://localhost:8545
ENV LAUNCHER_SCRIPT=../alto-launcher.sh

# Run the test suite
CMD ["pdm", "run", "pytest", "-rA", "-W", "ignore::DeprecationWarning", "--url", "${BUNDLER_URL}", "--entry-point", "${ENTRY_POINT}", "--ethereum-node", "${ETHEREUM_NODE}", "--launcher-script", "${LAUNCHER_SCRIPT}"]
