name: Release (Canary)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  canary:
    name: Release canary
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install test dependencies
        run: pnpm install

      - name: Setup .npmrc file
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Set alto version
        run: |
          jq --arg prop "workspaces" 'del(.[$prop])' package.json > package.tmp.json && rm package.json && cp package.tmp.json package.json && rm package.tmp.json
          cd src
          npm --no-git-tag-version version 0.0.0
          npm --no-git-tag-version version $(npm pkg get version | sed 's/"//g')-$(git branch --show-current | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//').$(date +'%Y%m%dT%H%M%S')
      - name: Build
        run: |
          pnpm run build:contracts && pnpm run build:esm && jq '. + {type: "module"}' ./src/package.json > ./src/package.tmp.json && mv ./src/package.tmp.json ./src/package.json

      - name: Publish alto to npm
        run: cd src && npm publish --access public --tag $(git branch --show-current | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ORG_PIMLICO_TOKEN }}
